---

- name: Create dir to store project files
  file:
    path: '{{ project_dir }}'
    state: directory
    mode: '0755'

- name: Initialize the Kubernetes cluster using kubeadm
  become: yes
  command: >
     kubeadm init
      --apiserver-advertise-address={{ ansible_host }}
      --apiserver-cert-extra-sans={{ ansible_host }}
      --node-name k8s-master
      --pod-network-cidr=10.244.0.0/16

- name: Create .kube dir
  file:
    path: /home/ansible/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf config file
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ansible/.kube/config
    remote_src: yes
    owner: ansible
    group: ansible
    mode: '0600'

- name: Download Flannel
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: '{{ project_dir }}/kube-flannel.yml'
    mode: '0644'

- name: Apply Flannel
  community.kubernetes.k8s:
    state: present
    src: '{{ project_dir }}/kube-flannel.yml'

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: >
    copy content="{{ join_command.stdout_lines[0] }}"
    dest="./join-command"

- include: metal_lb.yml
