---

# - name: Apply MetalLB manifest
#   command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.8/manifests/metallb.yaml

- name: Download MetalLB manifest to cluster
  get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/v0.8/manifests/metallb.yaml
    dest: '{{ project_dir }}/metal_lb_manifest.yml'
    mode: '0644'

- name: Apply MetalLB manifest
  community.kubernetes.k8s:
    state: present
    src: '{{ project_dir }}/metal_lb_manifest.yml'

- name: Apply MetalLB ConfigMap from template
  community.kubernetes.k8s:
    state: present
    template: metal_lb.j2.yml
